vapor/core/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from . import views

urlpatterns = patterns('',
   url(r'^$', TemplateView.as_view(template_name="core/frontpage.html"), name="home"),
   url(r'^id/(?P<steam_id>[\w-]+)/?$', views.VaporProfile, name="Profile"),
   url(r'^id/(?P<steam_id>[\w-]+)/tf2/?$', views.VaporTF2Backback, name="tf2backpack"),
)

vapor/dota2/urls.py
from __future__ import absolute_import
from django.conf.urls import *
from . import views

urlpatterns = patterns('',   
   url(r'^matches/?$', views.LatestMatchesView, name="public-matches"),
   url(r'^leagues/?$', views.LiveLeaguesView, name="leagues"),    
)

vapor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^admin42/', include(admin.site.urls)),
    url(r'^dota2/', include('vapor.dota2.urls', namespace='DOTA2')),
    url(r'^', include('vapor.core.urls', namespace='Core')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vapor/dota2/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_unicode, smart_str
from django.utils.translation import ugettext_lazy as _

class Hero(models.Model):
	name = models.CharField(max_length=255)
	localized_name = models.CharField(max_length=355)
	date_last_updated = models.DateTimeField(null=True, blank=True)
	
	class Meta:
	    db_table = 'dota2_heroes'
	    verbose_name_plural = 'Heroes'
	    
	def __unicode__(self):
	    return self.name
	    
class Ability(models.Model):
	name = models.CharField(max_length=255)
	localized_name = models.CharField(max_length=355)
	date_last_updated = models.DateTimeField(null=True, blank=True)

	class Meta:
	    db_table = 'dota2_abilities'
	    verbose_name_plural = 'Abilities'
	    
	def __unicode__(self):
	    return self.name

class Item(models.Model):
	name = models.CharField(max_length=255)
	localized_name = models.CharField(max_length=355)
	date_last_updated = models.DateTimeField(null=True, blank=True)

	class Meta:
	    db_table = 'dota2_items'
	    verbose_name_plural = 'Items'
	    
	def __unicode__(self):
	    return self.name

vapor/core/views.py
import functools
import steam
import re

from time import mktime
from datetime import datetime

from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404, render
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from steam import items
from steam import sim

import vapor.utils as steamutil

steam.api.key.set('870C28BC99B324034F4C0A9688311390')
steamutil.base.set_api_key('870C28BC99B324034F4C0A9688311390')

def VaporProfile(request, steam_id):
    vanity = steam.user.vanity_url(steam_id)
    id64 = str(vanity.id64)
    profile = steam.user.profile(id64)

    if profile.visibility == 3:
        games = steam.api.interface("IPlayerService").GetOwnedGames(steamid = id64, include_appinfo = 1, include_played_free_games = 1)
        game_count = games['response']['game_count']
        games_list = games['response']['games']

        games_played = []
        for game in games_list:
            if game['playtime_forever'] > 0:
                game['has_played'] = True
                games_played.append(game)
                
        context = { 'request': request, 'vanity_id': id64, 'game_count': game_count, 'games_list': games_list, 'games_played': games_played }
        return render_to_response('core/profile.html', context, context_instance=RequestContext(request))
    else:
        context = {'request': request,}
        return render_to_response('core/private.html', context, context_instance=RequestContext(request))


def VaporTF2Backback(request, steam_id):
    vanity = steam.user.vanity_url(steam_id)
    id64 = str(vanity.id64)
    profile = steam.user.profile(id64)
    if profile.visibility == 3:
        #bp = steam.api.interface("IEconItems_440").GetPlayerItems(steamid = id64)
        #backpack = steamutil.tf2.backpack(id64)
        BACKPACK_CACHE = '%s_BACKPACK_CACHE' % id64
        backpack = cache.get(BACKPACK_CACHE, None)
        if not backpack:
            backpack = steamutil.tf2.backpack(id64)
            cache.set(BACKPACK_CACHE, backpack, None) #Cache forever
        context = { 'request': request, 'vanity_id': id64, 'bp': backpack}
        return render_to_response('core/backpack.html', context, context_instance=RequestContext(request))
    else:
        context = {'request': request,}
        return render_to_response('core/private.html', context, context_instance=RequestContext(request))

vapor/dota2/views.py
import json
import urllib2
import functools
from time import mktime, strftime
from datetime import datetime
import requests

from gevent import monkey
monkey.patch_all()

from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404, render
from django.core.cache import cache
from django.views.decorators.cache import cache_page

import steam
from dota2py import api

key = '870C28BC99B324034F4C0A9688311390'
api.set_api_key(key)
steam.api.key.set(key)
RECENT_MATCHES = "https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?format=JSON&matches_requested=10&tournament_games_only=1&key="

def LatestMatchesView(request):

	#LATEST_MATCHES_CACHE = 'latest_matches_public'
	#match_data = cache.get(LATEST_MATCHES_CACHE, None)
	#if not match_data:
#		match_data = api.get_match_history(matches_requested=10, min_players=4)["result"]["matches"]
#		cache.set(LATEST_MATCHES_CACHE, match_data, 60 * 15) # 15 minutes
	match_data = steam.api.interface("IDOTA2Match_570").GetMatchHistory(matches_requested=10, min_players=4)

	context = {'request': request, 'match_data': match_data, }
	return render_to_response('dota2/recent_matches.html', context,
		context_instance=RequestContext(request))

def LatestMatchesViewForUser(request):
	account_id = int(api.get_steam_id("underlost")["response"]["steamid"])
	matches = api.get_match_history(account_id=None)["result"]["matches"]
	context = {'request': request, 'matches': matches, }
	return render_to_response('dota2/matches.html', context,
		context_instance=RequestContext(request))

def LiveLeaguesView(request):
	matches = api.get_live_league_games()["result"]
	context = {'request':request, 'matches': matches,}
	return render_to_response('dota2/matches.html', context,
		context_instance=RequestContext(request))

def SingleMatch(request, match_id):
	match = api.get_match_details(match_id[0]["match_id"])
	context = {'request': request, 'match':match,}
	return render_to_response('dota2/match_detail.html', context,
		context_instance=RequestContext(request))

def LeagueListingView(request):
	leagues = api.get_league_listing()
	context = {'request':request, 'leagues': leagues,}
	return render_to_response('dota2/leagues.html', context,
		context_instance=RequestContext(request))

def HeroListView(request):
	heroes = api.get_heroes()
	context = {'request': request, 'heroes': heroes,}
	return render_to_response('dota2/heroes.html', context,
		context_instance=RequestContext(request))

vapor/templates/base.html
<!DOCTYPE html>
 <html lang="en" class="no-js home">

<head>
<title>{% block title %}{% endblock %} vapor</title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="canonical" href="http://underlost.net/" />

<!-- Favicons -->
<link rel="shortcut icon" href="http://media.underlost.net/favicon.ico"/>

<!-- Meta -->
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="author" content="Tyler Rilling" />
<meta name="robots" content="all" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Experiments with Steam WebAPI" />

<link rel="stylesheet" href="/static/css/vapor.min.css" type="text/css" media="screen" />

<!-- Javascript -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/vapor.min.js"></script>

<script type="text/javascript">
			$(document).ready(function(){
				$('#paging_container1').pajinate();
			});
</script>

{% block extra %}{% endblock %}

 <script type="text/javascript">

   var _gaq = _gaq || [];
   _gaq.push(['_setAccount', 'UA-1247925-1']);
   _gaq.push(['_trackPageview']);

   (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();

 </script>
</head>

<body class="{% block page %}{% endblock %}">
    <div id="wrap">
    {% block content %}{% endblock %}
    <footer class="site-footer">
		<p>Site created by <a href="http://underlost.net">Tyler / Underlost</a>. Web API provided by <a href="http://www.valvesoftware.com/" class="external text" rel="nofollow">Valve Corporation</a>.</p>
	</footer>
    </div>
</body>
</html>

vapor/templates/core/backpack.html
{% extends 'base.html' %}{% load steamPersona %}{% load cache %}

{% block page %}profile{% endblock %}

{% block content %}
{% render_profile_head vanity_id %}
<div class="row">
	<div class="col-md-12">
	<ul class="list-inline itemlist">
	{% for item in bp reversed %}
		<li class="{{item.get_quality.prettystr|slugify}} item">
			<a href="#" rel="popover" title="{{item.get_name}}" data-content="{{item.get_description}}">
				<img src="{{item.get_image}}" width=70 heigh=70 />
			</a>
		</li>
		{% if forloop.counter|divisibleby:50 %}<hr class="linebreaker visible-md visible-lg" />{% endif %}
	{% endfor %}
	</ul>
	</div>
</div>
{% endblock %}

vapor/templates/core/frontpage.html
{% extends 'base.html' %}

{% block page %}index{% endblock %}

{% block content %}
	<header class="site-head-centered">
		<h1 title="vapor">vapor</h1>
	</header>
	<div id="frontpage">
		<p><strong>Vapor</strong> is a little experiment in my explorations of Valve's web apis. This site is mostly pointless, but may yield some interesting results from time to time.
			Below are the following experiments I've been toying with. For more information regarding the making of this site, check out the blog post/case study I wrote <a href="#">here</a>.
		</p>
	</div>
{% endblock %}

vapor/templates/core/profile.html
{% extends 'base.html' %}{% load steamPersona %}

{% block page %}profile{% endblock %}

{% block content %}
{% render_profile_head vanity_id %}

<h2>Total games: {{game_count}} <small>({{games_played|length}} played)</small></h2>

<ul class="media-list">
{% for game in games_list|dictsort:"playtime_forever" reversed %}
<li class="media">
	<div class="media-left">
		<a href="#">
			<img class="media-object img-rounded" src="http://media.steampowered.com/steamcommunity/public/images/apps/{{game.appid}}/{{game.img_icon_url}}.jpg" alt="{{game.name}}">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">{{game.name}}</h4>
		({{game.playtime_forever|sectodur}} played)
	</div>
</li>
{% endfor %}
</ul>
{% endblock %}

vapor/templates/core/templatetags/user_head.html
<header class="site-head-default">
	<div id="avatar"><img src="{{steam_profile.avatar_medium}}" /></div>
	<h1><a href="{{steam_profile.profile_url}}" title="View {{steam_profile.persona}}'s Steam Profile" id="profile-link">{{steam_profile.persona}} <span>({{steam_profile.real_name}})</span></a></h1>
	<div id="status">
		{% if steam_profile.current_game.gameid == None %}
			<span class="inchat">{% if status == 0 %}Offline (Last Online: {{last_online|date:"F j, Y"}}){% endif %}
			{% if steam_profile.status == 1 %}Online{% endif %}
			{% if steam_profile.status == 2 %}Busy{% endif %}
			{% if steam_profile.status == 3 %}Away{% endif %}
			{% if steam_profile.status == 4 %}Snooze{% endif %}</span>
		{% else %}
			<span class="ingame"><strong>In-Game:</strong> {{steam_profile.current_game.gameid}}</span>
		{% endif %}
	</div>
</header>

<nav class="navbar navbar-inverse">
	<ul class="nav navbar-nav">
		<li><a href="{% url 'Core:Profile' steam_profile.vanity %}">Games List</a></li>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Backpacks <span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="{% url 'Core:tf2backpack' steam_profile.vanity %}">Team Fortress 2</a></li>
				<li><a href="#">Dota 2</a></li>
				<li><a href="#">Portal 2</a></li>
			</ul>
		</li>
	</ul>
</nav>

vapor/templates/dota2/matches.html
{% extends 'base.html' %}{% load dota %}

{% block page %}matches{% endblock %}

{% block content %}
	<ul class="unstyled">
		{% for match in matches %}
			<li><h2>{{ match.match_id }}</h2>
				Match Starttime: {{ match.start_time }} <br />
				<strong>players:</strong>

				{% for player in match.players %}
				<ul>
					 <li>account id: {{ player.account_id|steam_name }}</li>
					 <li>hero id:{{ player.hero_id }}</li>
				</ul>
				{% endfor %}

				<hr />
			</li>
		{% endfor %}
	</ul>
{% endblock %}

vapor/templates/dota2/recent_matches.html
{% extends 'base.html' %}{% load dota %}

{% block page %}matches{% endblock %}

{% block content %}
<header class="site-head-default">
	<h1>Recent Matches</h1>
</header>
<ul>
{% for match in match_data.result.matches %}
	<li><h2>{{ match.match_id }}</h2>
		Match Starttime: {{ match.start_time }} <br />
		<strong>players:</strong>

		{% for player in match.players %}
		<ul>
			<li>{{ player.account_id|steam_name }} (id: {{ player.account_id }})</li>
			<li>hero: {{ player.hero_id|get_hero_name }}</br>
				hero id:{{ player.hero_id }}</li>
		</ul>
		{% endfor %}
	<hr />
	</li>
{% endfor %}
</ul>

{{match_data}}
{% endblock %}